version: '3'

services:
  ytb-summarizer:
    image: ytb-summarizer-dev:latest
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ytb-summarizer
    restart: unless-stopped
    command: uvicorn app:app --reload --port 80 --host 0.0.0.0
    ports:
      - "8000:80"
    environment:
      - GROQ_API_KEY=${GROQ_API_KEY}
      - SUMMARIZER_MODEL_NAME=${SUMMARIZER_MODEL_NAME}
      - ASSEMBLYAI_API_KEY=${ASSEMBLYAI_API_KEY}
    volumes:
      - ./src/:/app/
    depends_on:
      - redis-ytb-summarizer

  redis-ytb-summarizer:
    image: redis:6.2-alpine
    container_name: redis-ytb-summarizer
    restart: unless-stopped
    command: redis-server --loglevel warning
